idea:
    build: .
    labels:
        org.kurron.description: "Charles Proxy"
        org.kurron.version: "3.11.2"
    container_name: "charles"
    net: "host"
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/vagrant:/home/developer
    environment:
        DISPLAY: unix:0.0
    user: 1000:1000
